# Last edited on 2024-12-24 22:16:19 by stolfi

PROG := \
  fni_to_pnm

JS_LIBS := \
  libpst.a \
  libimg.a \
  libgeo.a \
  libgausol.a \
  libjs.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

