# Last edited on 2013-06-16 13:04:55 by stolfilocal

PROG := pnmfftfilter

JS_LIBS := \
  libimg.a \
  libgeo.a \
  libjs.a
  
OTHER_LIBS := \
  /usr/lib64/libfftw3.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

