# Last edited on 2023-01-14 11:55:14 by stolfi

PROG := pnmspectrum

JS_LIBS := \
  libimg.a \
  libgeo.a \
  libjs.a
  
OTHER_LIBS := \
  /usr/lib/x86_64-linux-gnu/libfftw3.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

