# Last edited on 2008-01-15 01:32:19 by stolfi

PROG := langev

JS_LIBS := \
  libimg.a \
  libgeo.a \
  libjs.a

OTHER_C_FLAGS := -pg
OTHER_LD_FLAGS := -pg

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

