# Last edited on 2024-12-20 19:37:42 by stolfi

PROG := \
  auclean

JS_LIBS := \
  libjsaudio.a \
  libgeo.a \
  libgausol.a \
  libjs.a \
  
OTHER_LIBS := \
  /usr/lib/x86_64-linux-gnu/libfftw3.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

