# Makefile 
# Last edited on 2020-10-31 20:13:33 by jstolfi

PROG := image_match_features
  
JS_LIBS := \
  libminn.a \
  libimg.a \
  libgeo.a \
  libjs.a
  
OTHER_LIBS := \
  /usr/lib/x86_64-linux-gnu/libjpeg.a \
  /usr/lib/x86_64-linux-gnu/libpng16.a \
  /usr/lib/x86_64-linux-gnu/libz.so 

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
