# Last edited on 2024-12-24 22:16:07 by stolfi

PROG := pnm_to_fni

JS_LIBS := \
  libpst.a \
  libimg.a \
  libgeo.a \
  libgausol.a \
  libjs.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

