# Last edited on 2023-02-24 04:08:52 by stolfi

PROG := \
  aufilter

JS_LIBS := \
  libgeo.a \
  libjs.a \
  libjsaudio.a \
  
OTHER_LIBS := \
  /usr/lib/x86_64-linux-gnu/libfftw3.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

