# Makefile 
# Last edited on 2017-10-25 21:23:48 by stolfilocal

PROG := multifok_analyze
  
JS_LIBS := \
  libmultifok.a \
  liblsq.a \
  libimg.a \
  libgeo.a \
  libjs.a
  
OTHER_LIBS := \
  /usr/lib64/libjpeg.so \
  /usr/lib64/libpng.so \
  /usr/lib64/libz.so

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
