# Last edited on 2023-09-23 11:42:10 by stolfi

PROG := pnmdiffop

JS_LIBS := \
  libimg.a \
  libgeo.a \
  libjs.a
  
# OTHER_C_FLAGS := -pg
# OTHER_LD_FLAGS := -pg

OTHER_C_FLAGS := -O3
OTHER_LD_FLAGS := 

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

