# Makefile 
# Last edited on 2023-02-04 11:42:26 by stolfi

PROG := multifok
  
JS_LIBS := \
  libdsm.a \
  libimg.a \
  libgeo.a \
  libjs.a
  
OTHER_LIBS := \
  /usr/lib/x86_64-linux-gnu/libjpeg.so \
  /usr/lib/x86_64-linux-gnu/libpng.so \
  /usr/lib/x86_64-linux-gnu/libz.so

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
