# Last edited on 2024-08-30 23:24:49 by stolfi

PROG := spegram

JS_LIBS := \
  libgeo.a \
  libjs.a \
  libjsaudio.a \
  
OTHER_LIBS := \
  /usr/lib/x86_64-linux-gnu/libfftw3.a
  
include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

