# Last edited on 2023-02-07 23:43:55 by stolfi

PROG := spegram

JS_LIBS := \
  libjs.a \
  libjsaudio.a \
  
OTHER_LIBS := \
  /usr/lib/x86_64-linux-gnu/libfftw3.a
  
include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

