# Last edited on 2025-04-24 14:19:57 by stolfi

PROG := make_grid_sheet

JS_LIBS := \
  libmkgr.a \
  libimg.a \
  libeps.a \
  libgeo.a \
  libgausol.a \
  libjs.a
  
OTHER_LIBS := \
  /usr/lib/x86_64-linux-gnu/libjpeg.a \
  /usr/lib/x86_64-linux-gnu/libpng16.a \
  /usr/lib/x86_64-linux-gnu/libz.so
  
include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
