# Last edited on 2020-11-29 20:52:41 by jstolfi

PROG := make_grid_sheet

JS_LIBS := \
  libmkgr.a \
  libimg.a \
  libeps.a \
  libgeo.a \
  libjs.a
  
OTHER_LIBS := \
  /usr/lib/x86_64-linux-gnu/libjpeg.a \
  /usr/lib/x86_64-linux-gnu/libpng16.a \
  /usr/lib/x86_64-linux-gnu/libz.so
  
include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
