#! /bin/bash
# Last edited on 2024-12-24 16:22:00 by stolfi

# cp -avi ../../COURSES/mc919-fi/0-TEST-GAMMA-0750.pgm                             gamma075.pgm
# cp -avi ../../COURSES/mc919-fi/0-TEST-LUM.ppm                                    huesdraw.ppm
# cp -avi ../../COURSES/mc919-fi/IN/arara.ppm                                      ararabri.ppm
# cp -avi ../../COURSES/mc919-fi/IN/frupq.ppm                                      frutaspq.ppm
# cp -avi ../../COURSES/mc919-fi/IN/fruta.ppm                                      frutasgd.ppm
# cp -avi ../../IB2/000/000/030/001.png                                            sblp1998.png
# cp -avi ../../IB2/000/000/036/003.png                                            fragbags.png
# cp -avi ../../IB2/000/000/036/004.png                                            fragtray.png
# cp -avi ../../IB2/000/000/038/053.png                                            fragbtc1.png
# cp -avi ../../IB2/000/000/039/188.png                                            voidbtc1.png
# cp -avi ../../IB2/000/000/039/726.png                                            handurna.png
# cp -avi ../../IB2/000/000/040/144.png                                            caramujo.png
# cp -avi ../../IB2/000/000/040/150.png                                            alunaiab.png
# cp -avi ../../IB2/000/000/049/000.png                                            spoofvms.png
# cp -avi ../../IB2/000/000/053/000.png                                            docentes.png
# cp -avi ../../IB2/000/000/054/001.png                                            cloudsky.png
# cp -avi ../../IB2/000/000/056/002.png                                            srcobliq.png
# cp -avi ../../IB2/000/000/067/011.png                                            treepond.png
# cp -avi ../../IB2/000/000/070/004.png                                            canyons1.png
# cp -avi ../../IB2/000/000/073/033.png                                            zvonicat.png
# cp -avi ../../IB2/000/000/083/000.png                                            dodeconf.png
# cp -avi ../../IB2/000/001/000/012.png                                            jupispot.png
# cp -avi ../../IB2/000/001/017/003.png                                            cezembre.png
# cp -avi ../../IB2/000/001/050/003.png                                            potbrmus.png
# cp -avi ../../IB2/000/001/058/000.png                                            fragsflp.png
# cp -avi ../../IB2/000/001/059/001.png                                            plantvms.png
# cp -avi ../../IB2/000/001/062/007.png                                            charsvms.png
# cp -avi ../../IB2/000/001/082/008.png                                            turkwmap.png
# cp -avi ../../IMG/geostereo/tests/photo/f0a-e.ppm                                fragf0ae.ppm
# cp -avi ../../IMG/geostereo/tests/photo/f1a-e.ppm                                fragf1ae.ppm
# cp -avi ../../IMG/pgmcolorize/tests/earthvis-in.pgm                              earthvis.pgm
# cp -avi ../../IMG/pnmalign/tests/abi-0.ppm                                       astolfi0.ppm
# cp -avi ../../IMG/pnmalign/tests/abi-1.ppm                                       astolfi1.ppm
# cp -avi ../../IMG/pnmalign/tests/abi-2.ppm                                       astolfi2.ppm
# cp -avi ../../IMG/pnmalign/tests/abi-3.ppm                                       astolfi3.ppm
# cp -avi ../../IMG/pnmfftfilter/tests/data/flo-1.ppm                              flower01.ppm
# cp -avi ../../IMG/pnmfftfilter/tests/data/rnd-2.ppm                              random01.ppm
# cp -avi ../../IMG/pnmfftfilter/tests/data/ula-1.ppm                              preslula.ppm
# cp -avi ../../IMG/pnmfield/tests/pnmadjust/data/2000-talossa-03-o.jpg            kingbobm.jpg
# cp -avi ../../IMG/pnmfield/tests/pnmadjust/data/eijistolfi-1-o.jpg               estolfi1.jpg
# cp -avi ../../IMG/pnmfield/tests/pnmadjust/data/jaburu-1-o.jpg                   msjaburu.jpg
# cp -avi ../../IMG/pnmfield/tests/pnmfield/gry-lin-ramp.ppm                       rampdia1.ppm
# cp -avi ../../IMG/pnmfield/tests/pnmfield/gry-lin-wave.ppm                       wavediag.ppm
# cp -avi ../../IMG/pnmfield/tests/pnmfield/rgb-lin-hWave.ppm                      wavehorz.ppm
# cp -avi ../../IMG/pnmfield/tests/pnmfield/rgb-lin-ramp.ppm                       rgbramps.ppm
# cp -avi ../../IMG/pnmfield/tests/pnmfield/rgb-lin-uniform.ppm                    uniforan.ppm
# cp -avi ../../IMG/pnmfield/tests/pnmfield/rgb-lin-vWave.ppm                      wavevert.ppm
# cp -avi ../../IMG/pnmfield/tests/pnmfield/rgb-lin-wave-igam.ppm                  wavedia2.ppm
# cp -avi ../../IMG/pnmfield/tests/pnmfield/rgb-lin-wave-ogam.ppm                  wavedia3.ppm
# cp -avi ../../IMG/pnmfield/tests/pnmfield/rgb-lin-wave.ppm                       wavedia4.ppm
# cp -avi ../../IMG/pnmfield/tests/pnmfield/rgb-lin-wavePair.ppm                   wavepair.ppm
# cp -avi ../../IMG/pnmhough/tests/mascaras.pgm                                    linmasks.pgm
# cp -avi ../../IMG/pnmhough/tests/teste-2-in.pgm                                  linerays.pgm
# cp -avi ../../IMG/pnmhough/tests/teste-5-in.pgm                                  linediag.pgm
# cp -avi ../../IMG/pnmhough/tests/teste-7-in.pgm                                  linevert.pgm
# cp -avi ../../IMG/pnmift/tests/data/bugeg.ppm                                    bugseggs.ppm
# cp -avi ../../IMG/pnmift/tests/data/corl1.pgm                                    coralbit.pgm
# cp -avi ../../IMG/pnmift/tests/data/figs1.pgm                                    figbunch.pgm
# cp -avi ../../IMG/pnmift/tests/data/fish1.pgm                                    fishes01.pgm
# cp -avi ../../IMG/pnmift/tests/data/flw04.ppm                                    flower04.ppm
# cp -avi ../../IMG/pnmift/tests/data/flw06.ppm                                    flower06.ppm
# cp -avi ../../IMG/pnmift/tests/data/flw23-1-seeds.pgm                            flseed23.pgm
# cp -avi ../../IMG/pnmift/tests/data/flw23.ppm                                    flower23.ppm
# cp -avi ../../IMG/pnmift/tests/data/flw33.ppm                                    flower33.ppm
# cp -avi ../../IMG/pnmift/tests/data/footb.ppm                                    football.ppm
# cp -avi ../../IMG/pnmift/tests/data/gecko.pgm                                    geckoeye.pgm
# cp -avi ../../IMG/pnmift/tests/data/lady3.pgm                                    ladybug3.pgm
# cp -avi ../../IMG/pnmift/tests/data/peter.pgm                                    peterbrg.pgm
# cp -avi ../../IMG/pnmift/tests/data/plank.pgm                                    plankton.pgm
# cp -avi ../../IMG/pnmift/tests/data/smurf.ppm                                    smurfs01.ppm
# cp -avi ../../IMG/pnmift/tests/data/sqirt.pgm                                    seasqirt.pgm
# cp -avi ../../IMG/pnmift/tests/data/srcpa.ppm                                    srcbuild.ppm
# cp -avi ../../IMG/pnmift/tests/data/straw.pgm                                    strawbit.pgm
# cp -avi ../../IMG/pnmift/tests/data/tatos.pgm                                    potatoes.pgm
# cp -avi ../../IMG/pnmift/tests/data/tree3.pgm                                    branches.pgm
# cp -avi ../../IMG/pnmift/tests/data/unifm.pgm                                    unifgray.pgm
# cp -avi ../../IMG/pnmpairtopng/tests/ic-logo-0.ppm                               iclogob0.ppm
# cp -avi ../../IMG/pnmpairtopng/tests/ic-logo-1.ppm                               iclogob1.ppm
# cp -avi ../../IMG/pnmpairtopng/tests/ramp-0.ppm                                  ramphorz.ppm
# cp -avi ../../IMG/pnmpairtopng/tests/ramp-1.ppm                                  rampvert.ppm
# cp -avi ../../IMG/pnmradist/tests/in/svga.ppm                                    gridsvga.ppm
# cp -avi ../../IMG/pnmtopsx/tests/lady3.png                                       ladybug3.png
# cp -avi ../../IMG/pnmwfilter/tests/in/f001r-blf.pgm                              vmsgray1.pgm
# cp -avi ../../IMG/pnmwfilter/tests/in/f001r-bot.pgm                              vmsgray2.pgm
# cp -avi ../../IMG/pnmwfilter/tests/in/f001r-brt.pgm                              vmsgray3.pgm
# cp -avi ../../IMG/pnmwfilter/tests/in/f001r-key.pgm                              vmsgray4.pgm
# cp -avi ../../IMG/pnmwfilter/tests/in/f116v-top.pgm                              vmsgray6.pgm
# cp -avi ../../IMG/pnmwfilter/tests/in/i0010.pgm                                  bricks01.pgm
# cp -avi ../../IMG/pnmwfilter/tests/in/i0037.pgm                                  europa01.pgm
# cp -avi ../../IMG/pnmwfilter/tests/in/i0045.pgm                                  fragsbit.pgm
# cp -avi ../../IMG/pnmwfilter/tests/in/i1000.pgm                                  miranda1.pgm
# cp -avi ../../IMG/pnmwfilter/tests/in/i1002.pgm                                  marsurf1.pgm
# cp -avi ../../IMG/pnmwfilter/tests/in/i1006.pgm                                  blpascal.pgm
# cp -avi ../../IMG/pnmwfilter/tests/in/i1009.pgm                                  cuneif01.pgm
# cp -avi ../../IMG/pnmwfilter/tests/in/i2001.pgm                                  vmsgray5.pgm
# cp -avi ../../IMG/pnmwiggle/tests/in/blk-1.pgm                                   synblock.pgm
# cp -avi ../../IMG/pnmxarith/tests/ramp-0.ppm                                     rampyell.ppm
# cp -avi ../../IMG/pnmxarith/tests/ramp-1.ppm                                     rampmage.ppm
# cp -avi ../../IMG/pnmxpad/tests/abi.pbm                                          astolfi4.pbm
# cp -avi ../../IMG/ppmoquant/tests/black.ppm                                      laclogb0.ppm
# cp -avi ../../IMG/ppmoquant/tests/white.ppm                                      laclogb1.ppm
# cp -avi ../../IMG/ppmtoymn/tests/in-amg.ppm                                      anatrain.ppm
# cp -avi ../../IMG/ppmtoymn/tests/in-app.ppm                                      applerow.ppm
# cp -avi ../../IMG/ppmtoymn/tests/in-grd.ppm                                      palette1.ppm
# cp -avi ../../IMG/volstereo/tests/m21.ppm                                        fragmirr.ppm
# cp -avi ../../JSLIBS/libimg/tests/encode_gamma/test-enc-BT709.pgm                encbt709.pgm
# cp -avi ../../JSLIBS/libimg/tests/misc_ops/in/dark.ppm                           balldark.ppm
# cp -avi ../../JSLIBS/libimg/tests/misc_ops/in/lite.ppm                           balllite.ppm
# cp -avi ../../JSLIBS/libimg/tests/misc_ops/in/thin.pgm                           linethin.pgm
# cp -avi ../../JSLIBS/libimg/tests/spectrum_table/in/real-0000-0000-0-orig.ppm    fernmaid.ppm
# cp -avi ../../JSLIBS/libimg/tests/spectrum_table/in/real-0000-0001-0-orig.ppm    flower40.ppm
# cp -avi ../../JSLIBS/libimg/tests/spectrum_table/in/real-0000-0002-0-orig.ppm    herbal01.ppm
# cp -avi ../../JSLIBS/libimg/tests/transform/test-1-ident-1-stripes-in-T-0.ppm    rgbweave.ppm
# cp -avi ../../JSLIBS/libimg/tests/transform/test-5-quadr-2-ripples-in-T-0.ppm    rgbrings.ppm
# cp -avi ../../JSLIBS/libimg/tests/transform/test-5-quadr-3-checker-in-T-0.ppm    rgbdotty.ppm
# cp -avi ../../JSLIBS/libleoimg/tests/test.pgm                                    doctyped.pgm
# cp -avi ../../MISC/loctel/demography/tests/bahia/bahia-pop.pgm                   popdensy.pgm
# cp -avi ../../MISC/loctel/demography/tests/bahia/bahia-std.pgm                   cityplan.pgm
# cp -avi ../../PST/fit_ellipse_to_photo/tests/data/balls-b-005-lum.pgm            balltrio.pgm
# cp -avi ../../PST/fit_ellipse_to_photo/tests/data/blocs-d-002-rgb.ppm            blocks01.ppm
# cp -avi ../../PST/fit_light_to_photo/tests/photo/balls-a/g-ms-a-0.png            ballmou0.png
# cp -avi ../../PST/fit_light_to_photo/tests/photo/balls-a/g-ms-a-1.png            ballmou1.png
# cp -avi ../../PST/fit_light_to_photo/tests/photo/balls-a/g-ms-a-2.png            ballmou2.png
# cp -avi ../../PST/fit_light_to_photo/tests/photo/balls-a/g-ms-a-nrm.png          ballnorm.png
# cp -avi ../../PST/fit_light_to_photo/tests/synth/balls-a/g-ms-a-0.png            mallmou4.png
# cp -avi ../../PST/fni_kodak_extract/tests/data/sonyh-a-6/img-r.png               kodaksc1.png
# cp -avi ../../PST/fni_lin_fit/tests/data/base-g.ppm                              ladybugs.ppm
# cp -avi ../../PST/fni_lin_fit/tests/data/base-o.ppm                              brickbit.ppm
# cp -avi ../../PST/fni_nodak_extract/tests/data/f-00.png                          nodaksc1.png
# cp -avi ../../PST/fni_photo_calib/tests/photo/balls-b-0/img-r.png                kodaksc2.png
# cp -avi ../../PST/fni_photo_calib/tests/photo/fragm-a-1/img-r.png                kodaksc3.png
# cp -avi ../../PST/pnm_to_fni/tests/ramp-1.pgm                                    rampgrys.pgm
# cp -avi ../../PST/pnm_to_fni/tests/rbow-1.ppm                                    rainbow1.ppm

mtsm="../../PST/make_test_slope_maps"

# cp -avi ../../IMG/make_bullseye/tests/out/test-image.pgm                         bullseye.pgm

# cp -avi ${mtsm}/tests/out/0512x0512/test-05-1-05-2-11-A-100-0000-0000-Z.pgm      sphdome1.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-06-1-05-2-11-A-100-0000-0000-Z.pgm      pentapyr.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-07-1-05-2-11-A-100-0000-0000-Z.pgm      circcone.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-08-1-05-2-11-A-800-0000-0000-Z.pgm      ripples1.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-09-1-05-2-11-A-300-0000-0000-Z.pgm      babelsft.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-11-1-05-2-11-A-100-0000-0000-Z.pgm      wavecos1.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-12-1-05-2-11-A-100-0000-0000-Z.pgm      wavesin1.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-13-1-05-2-11-A-100-0000-0000-Z.pgm      wavecos2.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-14-1-05-2-11-A-100-0000-0000-Z.pgm      wavesin2.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-15-1-05-2-11-A-100-0000-0000-Z.pgm      wavecos3.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-16-1-05-2-11-A-100-0000-0000-Z.pgm      wavesin3.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-17-1-05-2-11-A-100-0000-0000-Z.pgm      babelhrd.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-18-1-05-2-11-A-100-0000-0000-Z.pgm      cuberamp.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-20-1-05-2-11-A-100-0000-0000-Z.pgm      ringramp.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-21-1-05-2-11-A-900-0000-0000-Z.pgm      blurdots.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-22-1-05-2-11-A-500-0000-0000-Z.pgm      blutrian.pgm
# cp -avi ${mtsm}/tests/out/0512x0512/test-23-1-05-2-11-A-500-0000-0000-Z.pgm      blurpent.pgm

# cp -avi ../pgmcolorize/tests/out/grayramp-000-00255-0-1.ppm coloramp.ppm
# cp -avi ../pnmpairtopng/tests/ic-logo-0.ppm                 iclogobk.ppm
# 
# cp -avi ../langev/tests/out/amg-a-000000.ppm                langeva0.ppm
# cp -avi ../make-noisy-image/out/rnd-a.ppm                   noisegra.ppm
# cp -avi ../make-noisy-image/out/rnd-e.ppm                   noisegre.ppm

cp -avi ../../
