# Makefile 
# Last edited on 2012-01-25 04:38:16 by stolfilocal

PROG := image_stitch
  
JS_LIBS := \
  libminn.a \
  libimg.a \
  libgeo.a \
  libjs.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
