# Last edited on 2023-03-29 13:29:33 by stolfi

PROG := \
  fni_view

JS_LIBS := \
  libimg.a \
  libgeo.a \
  libjs.a

USE_GL := YES
USE_X11 := YES

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

