# Last edited on 2024-12-25 06:05:17 by stolfi

PROG := \
  fni_crop

JS_LIBS := \
  libpst.a \
  libimg.a \
  libgeo.a \
  libgausol.a \
  libjs.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

