# Last edited on 2010-03-13 14:53:25 by stolfi

PROG := pnmpairtopng

JS_LIBS := \
  libimg.a \
  libjs.a
  
OTHER_LIBS := \
  /usr/lib/libpng.so \
  /usr/lib/libz.so

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

