# Last edited on 2024-08-30 23:25:33 by stolfi

PROG := pnmpairtopng

JS_LIBS := \
  libimg.a \
  libgeo.a \
  libjs.a
  
OTHER_LIBS := \
  /usr/lib/libpng.so \
  /usr/lib/libz.so

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

