.TH pnmpairtopng 1 "03 dec 2003"
.IX pnmpairtopng
.SH NAME
pnmpairtopng - convert two ppm files into a partially transparent png
.SH SYNOPSIS
.B pnmpairtopng [-verbose] [-version] [-help]
.I blackpnmfile whitepnmfile
.fi
.SH DESCRIPTION
Reads two portable pixmaps, 
.I blackpnmfile
and
.I whitepnmfile.
Assumes that those images show the 
same scene rendered against a black and a white background, respectively,
and computes the foreground scene color and opacity of each pixel.
Writes that information to stdout, as a PNG image file with
alpha chanel.
.PP
The two images must have the same pixel type
(PPM, PGM, or PBM), the same dimensions, and the same
.I maxval.
The file name "-" denotes the standard input.
The output file will be in color (3 chennels + alpha) if the inputs are PPM files,
and grayscale (1 channel + alpha) otherwise.  The output will use 8 bits 
per channel if the input maxval is 255 or less, and 16 bits
per channel otherwise.  In any case, the output will be true-color
(i.e. not palette-based), and the alpha channel will be stored as 
an extra channel (i.e. not through a "tRNS" transparency chunk). 
.PP
The input images are assumed to use gamma = 1 (linear intensity
encoding), which is set as the output gamma.  The output samples
will be compressed with some internally chosen filter and compression level.
.PP
This is an intelligent program, because it does not try to be smart. 
All input information is preserved to the extent allowed by the 
output format. 
Any additional manipulations of the output file, such as the 
insertion of ancillary chunks, should be
performed by separate PNG tools.
.PP
All flags can be abbreviated to their shortest unique prefix.
.SH "SEE ALSO"
pnmtopng(1), ppmoquant(1), png(5), ppm(5)
.SH AUTHOR
Created by by J. Stolfi.
.PP
Copyright (C) 2003 by J. Stolfi.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
