# Last edited on 2023-03-07 19:19:11 by stolfi

PROG := pnmwfilter

JS_LIBS := \
  libimg.a \
  libgeo.a \
  libjs.a
  
OTHER_C_FLAGS := -pg
OTHER_LD_FLAGS := -pg

# OTHER_C_FLAGS := 
# OTHER_LD_FLAGS := 

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

